# resolver: lts-7.15
resolver: nightly-2017-01-30

packages:
- '.'

extra-deps: []

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

system-ghc: true
compiler-check: newer-minor

ghc-options:
  "*" : "-rtsopts -threaded"