resolver: lts-11.10
# resolver: nightly-2018-05-22

packages:
- '.'

extra-deps: []

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

system-ghc: true
compiler-check: newer-minor

ghc-options:
  "*" : "-rtsopts -threaded"